// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBn-zAlLwFKl73agc7MMmGmBsvRDLpAfVs',
    appId: '1:806793541052:web:d27512d9ad290f30d967b9',
    messagingSenderId: '806793541052',
    projectId: 'sisyphu-ea5a7',
    authDomain: 'sisyphu-ea5a7.firebaseapp.com',
    storageBucket: 'sisyphu-ea5a7.appspot.com',
    measurementId: 'G-L56ZL98JYX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvbPM_5d3Xl9shOKBg6YXV8_SO_To2L7U',
    appId: '1:806793541052:android:8ba0e303588ec692d967b9',
    messagingSenderId: '806793541052',
    projectId: 'sisyphu-ea5a7',
    storageBucket: 'sisyphu-ea5a7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADjwUsAZ_cBPin_vdXyr3THCCnIv3_kQ8',
    appId: '1:806793541052:ios:700eb618de3d521fd967b9',
    messagingSenderId: '806793541052',
    projectId: 'sisyphu-ea5a7',
    storageBucket: 'sisyphu-ea5a7.appspot.com',
    iosClientId: '806793541052-icin381qnko7bjeflp535go09h1dhndm.apps.googleusercontent.com',
    iosBundleId: 'com.io.sisyphu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADjwUsAZ_cBPin_vdXyr3THCCnIv3_kQ8',
    appId: '1:806793541052:ios:2eca42132cdc686bd967b9',
    messagingSenderId: '806793541052',
    projectId: 'sisyphu-ea5a7',
    storageBucket: 'sisyphu-ea5a7.appspot.com',
    iosClientId: '806793541052-ui33hdqibi3t78m4qf5nd5383cj8nh07.apps.googleusercontent.com',
    iosBundleId: 'com.example.sisyphu.RunnerTests',
  );
}
